export default `<p style="line-height: 1.2; text-align: center; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">KEBIJAKAN PRIVASI WEBSITE RSPI</span></strong></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Kebijakan Privasi ini akan melingkupi penjelasan mengenai bagaimana informasi pengguna website (&ldquo;</span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">&rdquo;) dikumpulkan, digunakan, dan dijaga kerahasiaannya oleh PT BINARA GUNA MEDIKTAMA dan/atau beserta anak perusahaannya (&ldquo;</span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">KAMI</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">&rdquo;) dengan tetap menghormati Hak PENGGUNA dalam menggunakan website Rumah Sakit Pondok Indah Group (&ldquo;</span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">WEBSITE</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">&rdquo;) KAMI.</span></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">A. Ruang Lingkup Kebijakan Privasi</span></strong></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Dengan menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, maka </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dianggap telah membaca </span><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini dan menyetujui mekanisme pengumpulan, penyimpanan, dan penggunaan Data Pribadi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> sebagaimana diatur dalam </span><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> dan rumah sakit &ndash; rumah sakit (termasuk Dokter didalamnya) yang tergabung dalam RS PONDOK INDAH GROUP (&ldquo;Rumah Sakit&rdquo;) dikelola oleh </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini mengatur penggunaan dan perlindungan informasi yang diberikan oleh </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> ketika menggunakan Layanan pada </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Apabila </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> meminta </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk memberikan informasi ketika menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, maka informasi tersebut itu hanya akan digunakan sesuai dengan </span><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> berhak untuk sewaktu-waktu mengubah, menghapus dan untuk menerapkan ketentuan baru pada </span><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini. </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> diharapkan untuk memeriksa halaman ini secara berkala untuk mengetahui perubahan tersebut. Dengan menggunakan layanan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> setelah terjadinya perubahan tersebut, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dianggap telah mengetahui dan menyetujui perubahan-perubahan ketentuan pada </span><strong><span style="font-size: 10pt;">Kebijakan Privasi</span></strong><span style="font-size: 10pt;"> ini.</span></p>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">B. Penggunaan Informasi</span></strong></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> menggunakan informasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk:&nbsp;</span></p>
<ol style="padding-inline-start: 48px;">
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menyediakan informasi kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> sesuai permintaan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berkaitan dengan pelayanan </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> pada masing-masing fitur di </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menyediakan informasi kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> lokasi dan acara atau kegiatan yang sedang dan/atau akan berlangsung di Rumah Sakit </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> yang terdekat dengan lokasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> ketika mengaktifkan lokasi koordinat/GPS.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menggunakan dan mengungkapkan informasi kesehatan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> sesuai keperluan operasi </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">. </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> dapat menggunakan dan mensirkulasikan informasi ini untuk tujuan peninjauan dan peningkatan kualitas Layanan dan pelayanan kesehatan yang </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> sediakan, atau kompetensi dan kualifikasi Dokter dan/atau staf profesional&nbsp; pada </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Memberikan informasi/mengirimkan e-mail, SMS, WhatsApp dan/atau media perpesanan lainnya yang berisi promosi secara berkala kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> bila terdapat suatu penawaran dan/atau promosi atas produk-produk baru, penawaran khusus, atau informasi lain yang menurut </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> diperlukan oleh </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menginformasikan kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> mengenai setiap perubahan dari </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, Layanan dan produk </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menggunakan informasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk menghubungi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dan mengingatkan mengenai penjadwalan Dokter yang dibuat melalui </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Menggunakan dan mengungkapkan informasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> jika diperlukan bagi tinjauan medis, jasa hukum, dan audit, meliputi penipuan dan deteksi penyalahgunaan dan program penyesuaian, serta perencanaan dan manajemen bisnis.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Catatan atau dokumentasi internal </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> yang disimpan di server </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">, baik di dalam maupun di luar wilayah Indonesia.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> akan menggunakan data-data yang dikumpulkan untuk pengolahan data statistik yang hasilnya akan digunakan untuk tinjauan medis maupun komersial. Pengolahan data statistik ini sebagian besar tidak akan mengungkapkan Data Pribadi, namun tidak tertutup kemungkinan akan adanya pengungkapan Data Pribadi dalam penelusuran hasil pengolahan statistik tersebut. Dengan menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dianggap telah memahami dan menyetujui penggunaan data-data tersebut.</span></p>
</li>
</ol>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> menjamin bahwa data dan informasi yang diberikan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> bersifat rahasia dan tidak akan disebarluaskan. Untuk mencegah akses tidak sah, </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> melakukan tindakan yang wajar dalam pengamanan fisik, elektronik, dan prosedur manajerial untuk melindungi informasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Informasi kesehatan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> hanya akan digunakan sehubungan dengan pelayanan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> beserta tinjauan medis Dokter dan </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> hanya akan mengumpulkan informasi yang dibutuhkan untuk menjalankan pelayanan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> menyimpan informasi pribadi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> selama informasi tersebut berhubungan dengan tujuan-tujuan yang dibutuhkan untuk kepentingan pelayanan </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">. Kerahasiaan informasi pribadi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> tentunya dianggap rahasia dan tidak akan disebarluaskan kecuali apabila diwajibkan oleh peraturan perundang-undangan yang berlaku.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Dengan menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dianggap telah menyetujui untuk mengijinkan pihak ketiga tertentu untuk menggunakan data </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk memberikan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> informasi mengenai barang dan jasa yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> perlukan. Pihak ketiga tersebut termasuk tetapi tidak terbatas pada:&nbsp;</span></p>
<ol style="padding-inline-start: 48px;">
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Asuransi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> yang akan membutuhkan bukti pelayanan yang telah diberikan dan / atau sebuah laporan medis sebelum dilakukan pembayaran kepada </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">: atau jika mereka memerlukan untuk otorisasi layanan atau rujukan.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Penyedia layanan pihak ketiga yang telah memberikan layanan kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> atau Dokter </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> (contoh layanan x-ray atau jasa uji laboratorium) untuk mendapatkan hasil pemeriksaan atau untuk kepentingan penerbitan tagihan.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><span style="font-size: 10pt;">Rekan bisnis </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">, seperti jasa penagihan atau yang mengerjakan layanan jasa administrasi untuk </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">. </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> memiliki perjanjian kerjasama dengan masing-masing rekan bisnis dan penyedia jasa diwajibkan untuk melindungi kerahasiaan dan keamanan dari informasi yang diteruskan pada mereka.</span></p>
</li>
</ol>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">C. Data Pribadi</span></strong></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> mengumpulkan informasi yang diberikan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> saat </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> membuat, mengirimkan surat elektronik / surel / e-mail kepada </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> atau meletakkan informasi atau konten lain di </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Informasi mengenai Data Pribadi yang wajib diisi oleh </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> saat melakukan Registrasi Akun dan/atau Layanan Janji Pertemuan dan/atau Layanan Pemeriksaan Kesehatan di </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> adalah sebagai berikut:&nbsp;</span></p>
<ul style="padding-inline-start: 48px;">
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Nomor kartu identitas (KTP, KITAS, KITAP, Passport)</span></p>
</li>
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Nama lengkap sesuai KTP</span></p>
</li>
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Jenis Kelamin</span></p>
</li>
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Tanggal lahir</span></p>
</li>
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Email</span></p>
</li>
<li style="list-style-type: disc; font-size: 10pt; font-family: 'Noto Sans Symbols', sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif;">Nomor Handphone</span></p>
</li>
</ul>
</li>
</ol>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Dengan menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> menjamin bahwa informasi yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berikan adalah akurat dan benar.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> berhak untuk melakukan verifikasi langsung kepada </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> atas informasi mengenai data diri yang telah disampaikan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> melalui </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Apabila informasi yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berikan tersebut ternyata tidak benar, maka </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> tidak bertanggung jawab atas segala akibat yang dapat terjadi sehubungan dengan pemberian dan penggunaan informasi tidak benar tersebut. Selanjutnya, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> membebaskan </span><strong><span style="font-size: 10pt;">KAMI </span></strong><span style="font-size: 10pt;">dari segala tuntutan, dakwaan dan akibat hukum yang ada sehubungan dengan pemberian informasi tidak benar tersebut.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> juga berhak mengumpulkan informasi ketika </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, termasuk tetapi tidak terbatas pada: alamat </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> yang merujuk dan aktivitas </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> di </span><strong><span style="font-size: 10pt;">WEBSITE </span></strong><span style="font-size: 10pt;">dan riwayat browing </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">. </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dapat mengaktifkan atau menonaktifkan layanan pengenalan lokasi saat </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> menggunakan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">D. Data Pengunjung</span></strong></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">WEBSITE</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> akan mengumpulkan informasi tentang penggunaan, seperti jumlah kunjungan dan aktivitas pengunjung. Data ini dikumpulkan dengan tujuan meningkatkan kenyamanan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> serta pelayanan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">KAMI</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">.</span></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">E. Koneksi Pengguna ke WEBSITE dan/atau APLIKASI Lain</span></strong></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Untuk keperluan referensi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">, pada </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> terdapat tautan ke aplikasi-aplikasi maupun website lain yang dicantumkan oleh </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">. Namun, ketika </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> menggunakan tautan-tautan tersebut, </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> tidak bertanggung jawab untuk melindungi privasi dan informasi apapun yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berikan ketika mengunjungi aplikasi-aplikasi tersebut. </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> juga tidak bertanggung jawab atas konten pada aplikasi-aplikasi tersebut, termasuk dampak yang ditimbulkan akibat mengakses aplikasi-aplikasi tersebut. </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> harus mempelajari dan membaca dengan hati-hati kebijakan penanganan informasi pribadi yang berlaku di aplikasi tersebut, maka apabila dikemudian hari muncul permasalahan hukum yang timbul akibat mengakses aplikasi-aplikasi tersebut, sepenuhnya menjadi tanggung jawab </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> membebaskan </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> dari segala tuntutan, dakwaan dan akibat hukum yang ada.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><span style="font-size: 10pt;">Untuk keperluan transaksi pembayaran, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> akan terkoneksi ke aplikasi yang dikelola oleh pihak Payment Gateway </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">. </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> senantiasa melakukan upaya yang wajar untuk melindungi informasi yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berikan untuk keperluan transaksi pembayaran tersebut.</span></p>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">F. Akses dan Perizinan Pada Perangkat Pengguna</span></strong></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Untuk perangkat Android dan iOS maupun perangkat lainnya yang digunakan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">, </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">WEBSITE</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> akan membutuhkan permission/izin akses untuk:</span></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; margin-top: 14pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Akses Internet &amp; Network State</span><span style="font-size: 10pt;"><br></span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> membutuhkan koneksi internet, sehingga </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> akan memantau kondisi internet &amp; network </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk dapat memberikan notifikasi, jika terjadi </span><em><span style="font-size: 10pt;">lost-connection</span></em><span style="font-size: 10pt;"> sewaktu waktu yang mengakibatkan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> tidak dapat berjalan (secara optimal), dan melihat riwayat browsing </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Akses Kamera&nbsp;</span></p>
<ol style="padding-inline-start: 48px;">
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> memerlukan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk menyertakan foto pada beberapa bagian dari </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dapat menggunakan Kamera sebagai salah satu media untuk dapat mengambil gambar.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Pemberian akses pada Kamera pada perangkat berfungsi bagi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk mengambil gambar dalam memilih foto profil </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">, foto kartu identitas, dan scan QRCode</span></p>
</li>
</ol>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Akses Foto, Galery dan Files&nbsp;</span></p>
<ol style="padding-inline-start: 48px;">
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> memerlukan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk menyertakan gambar dan/atau dokumen pada beberapa bagian dari </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">, </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dapat melihat pada gallery dan/atau file browser untuk mencari foto, gambar atau files terkait yang dibutuhkan.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> memerlukan </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk dapat menyimpan data-data yang di generate dari sisi </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> maupun aplikasi pihak ketiga yang terintegrasi dengan </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Pemberian akses pada foto, galeri dan files berfungsi bagi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk memilih foto profil dan/atau memilih dokumen pendukung yang dibutuhkan dalam Telekonsultasi dan/atau pendaftaran pelayanan kesehatan di Rumah Sakit.</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><span style="font-size: 10pt;">Pemberian akses foto, galeri dan files pada Perangkat juga akan memberikan akses "READ_EXTERNAL_STORAGE" &amp; "WRITE_EXTERNAL_STORAGE" pada perangkat </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> untuk </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> mengolah foto, gambar, dokumen (</span><em><span style="font-size: 10pt;">read &amp; write </span></em><span style="font-size: 10pt;">atau </span><em><span style="font-size: 10pt;">create file</span></em><span style="font-size: 10pt;">) yang diambil dari perangkat </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> menggunakan </span><em><span style="font-size: 10pt;">directory external storage</span></em><span style="font-size: 10pt;"> secara </span><em><span style="font-size: 10pt;">temporary</span></em><span style="font-size: 10pt;"> (file hasil olahan tersebut akan hilang sendirinya).</span></p>
</li>
</ol>
</li>
</ol>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;" start="4">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><span style="font-size: 10pt;">Akses Lokasi&nbsp;</span></p>
<ol style="padding-inline-start: 48px;">
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dapat melihat </span><em><span style="font-size: 10pt;">permission</span></em><span style="font-size: 10pt;"> yang digunakan oleh </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> dan menon-aktifkannya kapan pun melalui menu.&nbsp;</span></p>
</li>
<li style="list-style-type: lower-alpha; font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> membutuhkan data mengenai lokasi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> pada saat </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> membuka </span><strong><span style="font-size: 10pt;">WEBSITE</span></strong><span style="font-size: 10pt;"> dalam hal </span><em><span style="font-size: 10pt;">Find Hospitals</span></em><span style="font-size: 10pt;"> untuk tampilan Rumah Sakit </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> disekitar </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
</ol>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Jika ada akses yang tidak diberikan oleh </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">, maka ada kemungkinan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">WEBSITE</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> tidak dapat beroperasi atau berfungsi dengan optimal.</span></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">G. Upaya Pengamanan Data Pribadi</span></strong></p>
<ol style="margin-top: 0px; margin-bottom: 0px; padding-inline-start: 48px;">
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 0pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> senantiasa melakukan upaya yang wajar untuk menjaga Data Pribadi yang </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> berikan kepada </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> aman dan tidak dapat digunakan oleh pihak-pihak yang tidak bertanggungjawab sesuai dengan ketentuan Peraturan Perundang-Undangan yang berlaku.</span></p>
</li>
<li style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">
<p style="line-height: 1.2; text-align: justify; margin-top: 0pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> akan menyimpan data pribadi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;"> dalam server database </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;">, baik di dalam maupun di luar negeri, untuk memberikan perlindungan yang wajar berdasarkan penilaian </span><strong><span style="font-size: 10pt;">KAMI</span></strong><span style="font-size: 10pt;"> dari penyalahgunaan atau penghilangan Data Pribadi </span><strong><span style="font-size: 10pt;">PENGGUNA</span></strong><span style="font-size: 10pt;">.</span></p>
</li>
</ol>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">H. Hukum Yang Berlaku</span></strong></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Kebijakan Privasi</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> ini diatur berdasarkan hukum Republik Indonesia dan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> diwajibkan tunduk kepada semua peraturan yang berlaku di Indonesia.</span></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">I. Pertanyaan, Keluhan dan Kontak</span></strong></p>
<p style="line-height: 1.2; text-align: justify; margin-top: 14pt; margin-bottom: 14pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Jika </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> memiliki pertanyaan tentang </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Kebijakan Privasi</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> ini, peraturan-peraturan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">KAMI</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">, hak </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">, dan hubungan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">PENGGUNA</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> dengan </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">WEBSITE</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">, silahkan menghubungi </span><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">KAMI</span></strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);"> melalui informasi di bawah ini:</span></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 8pt;"><strong><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Rumah Sakit Pondok Indah Group</span></strong></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Jalan Metro Duta Kavling UE</span></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Jakarta Selatan, DKI Jakarta 12310</span></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">Indonesia</span></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><a style="text-decoration: none;" href="mailto:cs@rspondokindah.co.id"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0); text-decoration: underline; text-decoration-skip-ink: none;">cs@rspondokindah.co.id</span></a></p>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Tahoma, sans-serif; color: rgb(0, 0, 0);">+62 21 765 7525</span></p>`;