export const endpoints = {
	auth: '/auths/login',
	register: '/auths/register',
	verifyEmail: '/auths/verify-email',
	reVerifyEmail: '/auths/request-verify',
	pin: '/patients/pin',
	profile: '/patients/profile',
	otp: '/auths/otp',
	article: '/news',
	registerOnboard: '/patients/on-boarding',
	findDoctor: '/find/doctor',
	doctors: '/doctors',
	forgotPassword: '/auths/forgot-pass',
	banner: '/banners',
	facilities: '/facilities',
	centerOfExcellences: '/center-of-excellences',
	events: '/events',
	awards: '/awards',
	hospital: '/hospital',
	newsFacilities: '/news-facilities',
	facilityHospital: '/facilities-hospitals/facility',
	patients: '/patients',
	newsCenterOfExcellence: '/center-of-excellences-news/news',
	specialities: '/specialities',
	doctorSchedule: '/books/doctor-detail',
	doctorTimeSlot: '/books/time-slot',
	bookAppointment: '/books',
	contactUs: '/contact-us',
	generalUploads: '/uploads',
	updatePassword: '/patients/update-password',
	updateAvatar: '/patients/update-profile',
};
export default endpoints;