import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Lato } from 'next/font/google';

import StyledComponentsRegistry from '@/lib/registry';
import FacebookPixel from '@/components/FacebookPixel';
import '@/styles/globals.css';

type Props = {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: 'RS Pondok Indah',
  description: 'Generated by create next app',
};

const lato = Lato({
  subsets: ['latin'],
  fallback: ['Arial', 'sans-serif'],
  weight: ['100', '300', '400', '700', '900']
});

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={ lato.className } suppressHydrationWarning>
        <StyledComponentsRegistry>{ children }</StyledComponentsRegistry>

        <FacebookPixel />
      </body>
    </html>
  );
}
